baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"
disableRSS = true

[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04 -0700"
    avatarImg       = "images/avatar.jpg"

    # Metadata mostly used in document's head
    description = "Homepage and blog by Aumkar Prajapati."
    keywords = "homepage, blog, software, devops, development, programming"
    images = [""]

    # Social Icons
    [[params.social]]
    name = "github"
    url  = "https://github.com/aumkarpraja"

    [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/aumkar-prajapati-ba037492"
    
    [[params.social]]
    name = "email"
    url  = "mailto:me@aumkar.ca"

    # Directory name of your blog content (default is `content/posts`)
    contentTypeName = "posts"
    # Default theme "light" or "dark"
    defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Aumkar Prajapati"
    subtitle = "DevOps Specialist @ Indellient"
    keywords = ""
    homeSubtitle = "DevOps Specialist @ Indellient"
    copyright = "Aumkar Prajapati"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd /home/aumkar/"
      logoHomeLink = "/"

	# You can create a language based menu
    [languages.en.menu]
        [[languages.en.menu.main]]
            identifier = "about"
            name = "about"
            url = "/about"
        [[languages.en.menu.main]]
            identifier = "posts"
            name = "posts"
            url = "/posts"
        [[languages.en.menu.main]]
            identifier = "resume"
            name = "resume"
            url = "res/aumkar_resume.pdf"

# And you can even create generic menu
[menu]
    [[menu.main]]
        identifier = "about"
        name       = "About"
        url        = "/about"
    [[menu.main]]
        identifier = "blog"
        name       = "Blog"
        url        = "/posts"